#!/usr/bin/env bash
mkdir -p dist
echo "build src/ldpx.ls -> dist/ldpx.js ..."
./node_modules/.bin/lsc -cbp src/ldpx.ls > dist/ldpx.js
echo "build src/ldpx.styl -> dist/ldpx.css ..."
./node_modules/.bin/stylus -p src/ldpx.styl > dist/ldpx.css
echo "minifying ldpx.js ..."
./node_modules/.bin/uglifyjs dist/ldpx.js > dist/ldpx.min.js
echo "minifying ldpx.css ..."
./node_modules/.bin/uglifycss dist/ldpx.css > dist/ldpx.min.css
echo "deploy into local web ..."
mkdir -p web/static/assets/lib/
cp -R dist/* web/static/assets/lib/
echo "done."

